country_language = {
	'Albania': 'Albanian',
	'Armenia': 'Armenian',
	'Austria': 'German',
	'Australia': 'English',
	'Bosnia': 'Bosnian',        # Croatian / Serbian
	'Bulgaria': 'Bulgarian',
	'Canada': 'English',        # French, hard
	'China': 'Chinese',
	'Croatia': 'Croatian',
	'Czech': 'Czech',
	'Cyprus': 'Greek',          # Turkish, hard
	'Denmark': 'Danish',
	'Estonia': 'Estonian',
	'Finland': 'Finish',
	'France': 'French',
	'Georgia': 'Georgian',
	'Germany': 'German',
	'Greece': 'Greek',
	'Hungary': 'Hungarian',
	'Iceland': 'Icelandic',
	'India': 'Hindi',           # English, too many
	'Italy': 'Italian',
	'Ireland': 'English',
	'Israel': 'Hebrew',
	'Latvia': 'Latvian',
	'Lithuania': 'Lithuanian',
	'Macedonia': 'Macedonian',  # Albanian
	'Malta': 'Maltese',
	'Mexico': 'Spanish',
	'Moldova': 'Moldovan',
	'Montenegro': 'Montenegrin',
	'Netherlands': 'Dutch',
	'NewZealand': 'English',
	'Norway': 'Norwegian',
	'Poland': 'Polish',
	'Portugal': 'Portuguese',
	'Romania': 'Romanian',
	'Russia': 'Russian',
	'Serbia': 'Serbian',
	'Slovenia': 'Slovenian',
	'Slovakia': 'Slovak',
	'Spain': 'Spanish',
	'Sweden': 'Swedish',
	'Turkey': 'Turkish',
	'UK': 'English',
	'Ukraine': 'Ukrainian',
	'US': 'English',
	'Vietnam': 'Vietnamese'
}

language_family = {
	'Albanian': 'Other',
	'Armenian': 'Other',
	'German': 'Germanic',
	'English': 'English',
	'Bosnian': 'Slavic',
	'Bulgarian': 'Slavic',
	'Chinese': 'Other',
	'Croatian': 'Slavic',
	'Czech': 'Slavic',
	'Greek': 'Other',
	'Danish': 'Germanic',
	'Estonian': 'Slavic',
	'Finish': 'Other',
	'French': 'Latin',
	'Georgian': 'Other',
	'Hungarian': 'Other',
	'Icelandic': 'Germanic',
	'Hindi': 'Other',
	'Italian': 'Latin',
	'Hebrew': 'Other',
	'Latvian': 'Slavic',
	'Lithuanian': 'Slavic',
	'Macedonian': 'Slavic',
	'Maltese': 'Other',
	'Moldovan': 'Latin',
	'Spanish': 'Latin',
	'Romanian': 'Latin',
	'Montenegrin': 'Slavic',
	'Dutch': 'Germanic',
	'Norwegian': 'Germanic',
	'Polish': 'Slavic',
	'Portuguese': 'Latin',
	'Russian': 'Slavic',
	'Serbian': 'Slavic',
	'Slovenian': 'Slavic',
	'Slovak': 'Slavic',
	'Swedish': 'Germanic',
	'Turkish': 'Other',
	'Ukrainian': 'Slavic',
	'Vietnamese': 'Other'
}

is_native = {
	'English': 'Native',
	'Slavic': 'NonNative',
	'Latin': 'NonNative',
	'Germanic': 'NonNative',
	'Other': 'NonNative'
}

lang_enum = {
	'Albanian':    0,
	'Armenian':    1,
	'German':      2,
	'English':     3,
	'Bosnian':     4,
	'Bulgarian':   5,
	'Chinese':     6,
	'Croatian':    7,
	'Czech':       8,
	'Greek':       9,
	'Danish':      10,
	'Estonian':    11,
	'Finish':      12,
	'French':      13,
	'Georgian':    14,
	'Hungarian':   15,
	'Icelandic':   16,
	'Hindi':       17,
	'Italian':     18,
	'Hebrew':      19,
	'Latvian':     20,
	'Lithuanian':  21,
	'Macedonian':  22,
	'Maltese':     23,
	'Moldovan':    24,
	'Spanish':     25,
	'Romanian':    26,
	'Montenegrin': 27,
	'Dutch':       28,
	'Norwegian':   29,
	'Polish':      30,
	'Portuguese':  31,
	'Russian':     32,
	'Serbian':     33,
	'Slovenian':   34,
	'Slovak':      35,
	'Swedish':     36,
	'Turkish':     37,
	'Ukrainian':   38,
	'Vietnamese':  39
}

family_enum = {
	'English':  0,
	'Slavic':   1,
	'Latin':    2,
	'Germanic': 3,
	'Other':    4
}

is_native_enum = {
	'Native':       0,
	'NonNative':    1
}
